---
      - name: add user and create ssh key
        user: name=ivan
      - name: create authorized_keys from file that just downloaded
        authorized_key: user=ivan key=https://github.com/ivannieto.keys
