---
      - name: add user and create ssh key
        user: name=$USER
      - name: create authorized_keys from file that just downloaded
        authorized_key: user=$USER key=https://github.com/ivannieto.keys
