---

- name: Add Zeal repository
  apt_repository: repo="ppa:zeal-developers/ppa" state=present

- name: Install Zeal
  apt: name=zeal state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
