---
- include: ubuntu.yml

- name: Start and enable service
  service: name=mysql state=started enabled=yes

- include: mysql_secure_installation.yml
  when: mysql_secure_installation and mysql_root_password is defined
