---

- name: Install Flatabulous
  git: repo=https://github.com/andreisergiu98/arc-flatabulous-theme dest=/usr/share/themes/Flatabulous update=yes accept_hostkey=yes
  register: arch_flatabulous_git

- name: Set GTK Theme to Flatabulous
  command: "gsettings set org.gnome.desktop.interface gtk-theme Arc-Flatabulous-Darker"
  become: true
  become_user: "{{ ansible_env.USER }}"
  changed_when: arch_flatabulous_git.changed

- name: Set Windows Manager Theme to Flatabulous
  command: "gsettings set org.gnome.desktop.wm.preferences theme Arc-Flatabulous-Darker"
  become: true
  become_user: "{{ ansible_env.USER }}"
  changed_when: arch_flatabulous_git.changed
