---

- name: Add Tilix repository
  apt_repository: repo="ppa:webupd8team/terminix" state=present

- name: Install Tilix
  apt:  name=tilix state=latest update_cache=yes cache_valid_time={{ aptcachetime }}

- name: Fix VTE config
  shell: ln -s /etc/profile.d/vte-2.91.sh /etc/profile.d/vte.sh
  become: true

- name: Append VTE config to bashrc
  lineinfile:
    dest: ~/.bashrc
    line: "{{ vte.config }}"
    state: present

- name: Append VTE config to bashrc
  lineinfile:
    dest: ~/.zshrc
    line: "{{ vte.config }}"
    state: present
